# add current directory to the compiler included directories when compiling the given target.
target_include_directories(${CURRENT_EXE_NAME} PUBLIC
        # arm directories
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/CMSIS_5/CMSIS/Core/Include
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/littlefs
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/littlefs/config
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/include/mbedtls/
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/include/psa
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/include

        # aws directories
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/amazon-freertos/demos/dev_mode_key_provisioning/include
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS/Source/include
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/coreMQTT/source/include
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/coreMQTT/source/interface/
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/network_transport/tcp_sockets_wrapper/include
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/network_transport/
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/corePKCS11/source/dependency/3rdparty/mbedtls_utils
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/corePKCS11/source/dependency/3rdparty/pkcs11
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/corePKCS11/source/include
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/include/
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/include/portable/Compiler/GCC
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/include/portable/Compiler/IAR
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Utilities/logging
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/VisualStudio_StaticProjects/MbedTLS

        # board directory
        ${CMAKE_CURRENT_LIST_DIR}/ra/board/ra6m5_ck/

        # fsp directories
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/inc/
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/inc/api/
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/inc/instances/
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/cmsis/Device/RENESAS/Include
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/ra6m5
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/common
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/private/inc
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/public/inc
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_freertos_plus_tcp/
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_freertos_port/
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/inc/
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_zmod4xxx/
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_zmod4xxx/iaq_1st_gen/
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_zmod4xxx/oaq_1st_gen/

        # ra_cfg directories
        ${CMAKE_CURRENT_LIST_DIR}/ra_cfg/arm/
        ${CMAKE_CURRENT_LIST_DIR}/ra_cfg/arm/littlefs
        ${CMAKE_CURRENT_LIST_DIR}/ra_cfg/arm/mbedtls
        ${CMAKE_CURRENT_LIST_DIR}/ra_cfg/aws/
        ${CMAKE_CURRENT_LIST_DIR}/ra_cfg/fsp_cfg/
        ${CMAKE_CURRENT_LIST_DIR}/ra_cfg/fsp_cfg/bsp/

        # ra_gen directory
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/
)

target_sources(${CURRENT_EXE_NAME} PUBLIC
        # arm sources
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/littlefs/lfs.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/littlefs/lfs_util.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/pem.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/padlock.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/md.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/lms.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/aesce.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_client.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/memory_buffer_alloc.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/debug.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_aead.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_driver_wrappers.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ecjpake.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/bignum_mod_raw.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_mac.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/pkcs5.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ecp.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/pkcs7.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ecdh.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ctr_drbg.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/pkparse.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/platform_util.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/mps_reader.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/cipher_wrap.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/entropy_poll.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/pk_wrap.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/aesni.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/bignum_mod.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/mps_trace.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/aria.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/lmots.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_hash.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ccm.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/entropy.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/bignum.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/platform.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/pkwrite.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/camellia.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/dhm.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/des.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/chacha20.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/bignum_core.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_ecp.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ecp_curves.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/nist_kw.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/asn1write.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_pake.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/pkcs12.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/constant_time.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/pk.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/chachapoly.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_cipher.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/aes.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/cmac.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/cipher.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/net_sockets.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/base64.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/hash_info.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/md5.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/oid.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/gcm.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ecdsa.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_rsa.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/hmac_drbg.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/error.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/hkdf.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/poly1305.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/asn1parse.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_se.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_slot_management.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_crypto_storage.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_its_file.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/psa_util.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ripemd160.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/rsa.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/rsa_alt_helpers.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/sha1.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/sha256.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/sha512.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_cache.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_ciphersuites.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_client.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_cookie.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_msg.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_ticket.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_tls.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_tls12_client.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_tls12_server.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_tls13_client.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_tls13_generic.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_tls13_keys.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/ssl_tls13_server.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/threading.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/timing.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/version.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/version_features.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/x509.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/x509_create.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/x509_crl.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/x509_csr.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/x509write_crt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/arm/mbedtls/library/x509write_csr.c

        # aws sources
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/amazon-freertos/demos/dev_mode_key_provisioning/src
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS/Source/portable/MemMang/heap_4.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS/Source/list.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS/Source/queue.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS/Source/event_groups.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS/Source/tasks.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS/Source/stream_buffer.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS/Source/timers.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/coreMQTT/source/core_mqtt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/coreMQTT/source/core_mqtt_serializer.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/coreMQTT/source/core_mqtt_state.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/network_transport/tcp_sockets_wrapper/ports/freertos_plus_tcp/tcp_sockets_wrapper.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_bio_tcp_sockets_wrapper.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/Application-Protocols/network_transport/transport_mbedtls_pkcs11.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/corePKCS11/source/dependency/3rdparty/mbedtls_utils/mbedtls_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/corePKCS11/source/portable/mbedtls/core_pkcs11_mbedtls.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/corePKCS11/source/core_pkcs11.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/corePKCS11/source/core_pki_utils.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/portable/BufferManagement/BufferAllocation_2.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_ARP.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_BitConfig.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCP.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCPv6.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Cache.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Callback.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Networking.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Parser.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_ICMP.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_IP.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_IP_Timers.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_IP_Utils.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv4.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv4_Sockets.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv4_Utils.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv6.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv6_Sockets.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_IPv6_Utils.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_ND.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_RA.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_Routing.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_Stream_Buffer.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP_IPv4.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP_IPv6.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Reception.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_State_Handling.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_State_Handling_IPv4.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_State_Handling_IPv6.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Transmission.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Transmission_IPv4.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Transmission_IPv6.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Utils.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Utils_IPv4.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_Utils_IPv6.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_WIN.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_Tiny_TCP.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IP.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IPv4.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IPv6.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/aws/FreeRTOS/FreeRTOS-Plus/VisualStudio_StaticProjects/MbedTLS/mbedtls_freertos_port.c

        # board sources
        ${CMAKE_CURRENT_LIST_DIR}/ra/board/ra6m5_ck/board_init.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/board/ra6m5_ck/board_leds.c

        # fsp sources
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/cmsis/Device/RENESAS/Source/startup.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/cmsis/Device/RENESAS/Source/system.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_clocks.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_common.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_delay.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_group_irq.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_guard.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_io.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_irq.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_register_protection.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_rom_registers.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_sbrk.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/bsp/mcu/all/bsp_security.c

        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_cgc/r_cgc.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_ether/r_ether.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_ether_phy/targets/DP83620/r_ether_phy_target_dp83620.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_ether_phy/targets/ICS1894/r_ether_phy_target_ics1894.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_ether_phy/targets/KSZ8041/r_ether_phy_target_ksz8041.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_ether_phy/targets/KSZ8091RNB/r_ether_phy_target_ksz8091rnb.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_ether_phy/r_ether_phy.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_flash_hp/r_flash_hp.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_gpt/r_gpt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_icu/r_icu.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_iic_master/r_iic_master.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_ioport/r_ioport.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/adaptors/r_sce_adapt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func000.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func001.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func002.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func027.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func028.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func031.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func043.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func044.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func048.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func049.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func050.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func051.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func052.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func053.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func054.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func057.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func058.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func059.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func060.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func061.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func062.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func063.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func064.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func065.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func066.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func067.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func068.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func070.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func071.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func074.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func075.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func076.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func077.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func080.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func081.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func082.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func100.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func101.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func102.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func103.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func200.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func202.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func205.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func206.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func207.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func300.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func301.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func302.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func304.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func307.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func308.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func309.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func310.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func311.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func312.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func313.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func314.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func315.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func316.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func317.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func318.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func319.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func320.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func321.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func322.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func323.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func324.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_func325.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p00.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p01.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p2b.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p02.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p6e.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p7b.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p07.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p08.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p9a.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p9b.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p15.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p16.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p17.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p20.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p21.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p26.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p29a.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p29f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p29i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p29t.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p29u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p32a.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p32f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p32i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p32t.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p32u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p34a.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p34f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p34i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p34t.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p34u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p36a.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p36f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p36i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p36t.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p36u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p40.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p41f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p41i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p41u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p44f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p44i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p44u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p47f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p47i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p47u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p50f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p50i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p50u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p56.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p57.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p72.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p76f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p76i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p76u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p79.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p83a.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p83f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p83i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p83t.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p83u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p85a.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p85f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p85i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p85t.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p85u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p89f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p89i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p89u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p92.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p95f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p95i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p95u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p98f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p98i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_p98u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pa1f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pa1i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pa1u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pa4f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pa4i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pa4u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pa7f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pa7i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pa7u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb0f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb0i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb0u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb3f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb3i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb3u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb6f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb6i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb6u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb9f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb9i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pb9u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pc2f.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pc2i.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pc2u.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pf0.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pf1.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pf4.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pf5.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pf6.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_pf9.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/hw_sce_p_subprc01.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive/s_flash2.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sce_key_injection/r_sce_key_injection.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/r_sci_uart/r_sci_uart.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_aws_pkcs11_pal_littlefs/rm_aws_pkcs11_pal_littlefs.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_comms_i2c/rm_comms_i2c.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_comms_i2c/rm_comms_i2c_driver_ra.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_freertos_plus_tcp/NetworkInterface.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_freertos_port/port.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_hs300x/rm_hs300x.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_hs300x/rm_hs300x_ra_driver.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_littlefs_flash/rm_littlefs_flash.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_mbedtls/x509_crt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_ob1203/rm_ob1203.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_ob1203/rm_ob1203_ra_driver.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_ob1203/ppg_mode/rm_ob1203_ppg_mode.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_ob1203/proximity_mode/rm_ob1203_proximity_mode.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/aes_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/aes_alt_process.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/aes_vendor.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/asymmetric_vendor.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/ccm_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/ccm_alt_process.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/cipher_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/cmac_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/ctr_drbg_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/ecdh_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/ecdsa_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/ecdsa_alt_process.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/ecp_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/ecp_alt_process.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/ecp_curves_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/gcm_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/gcm_alt_process.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/platform_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/rm_psa_crypto.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/rsa_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/rsa_alt_process.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/sha256_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/sha256_alt_process.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/sha512_alt.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/sha512_alt_process.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/trng_entropy.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_psa_crypto/vendor.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_zmod4xxx/iaq_1st_gen/rm_zmod4410_iaq_1st_gen.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_zmod4xxx/oaq_1st_gen/rm_zmod4510_oaq_1st_gen.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_zmod4xxx/rm_zmod4xxx.c
        ${CMAKE_CURRENT_LIST_DIR}/ra/fsp/src/rm_zmod4xxx/rm_zmod4xxx_ra_driver.c

        # ra_gen sources
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/cloud_app_thread.c
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/common_data.c
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/console_thread.c
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/hal_data.c
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/main.c
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/oximeter_thread.c
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/pin_data.c
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/sensor_thread.c
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/vector_data.c
        ${CMAKE_CURRENT_LIST_DIR}/ra_gen/zmod_thread.c
)